name: OfflineRL
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - binutils_impl_linux-64=2.39=he00db2b_1
  - binutils_linux-64=2.39=h5fc0e48_13
  - ca-certificates=2025.12.2=h06a4308_0
  - certifi=2024.8.30=pyhd8ed1ab_0
  - conda-gcc-specs=9.5.0=haf979b4_19
  - gcc=9.5.0=h1fea6ba_13
  - gcc_impl_linux-64=9.5.0=h99780fb_19
  - gcc_linux-64=9.5.0=h4258300_13
  - gxx=9.5.0=h1fea6ba_13
  - gxx_impl_linux-64=9.5.0=h99780fb_19
  - gxx_linux-64=9.5.0=h43f449f_13
  - kernel-headers_linux-64=3.10.0=he073ed8_18
  - ld_impl_linux-64=2.39=hcc3a1bd_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=he0feb66_16
  - libgcc-devel_linux-64=9.5.0=h0a57e50_19
  - libgcc-ng=15.2.0=h69a702a_16
  - libgomp=15.2.0=he0feb66_16
  - libsanitizer=9.5.0=h2f262e1_19
  - libstdcxx=15.2.0=h934c35e_16
  - libstdcxx-devel_linux-64=9.5.0=h0a57e50_19
  - libstdcxx-ng=15.2.0=hdf11a46_16
  - libxcb=1.17.0=h9b100fa_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.6.0=h26f9b46_0
  - pip=24.2=py38h06a4308_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.8.20=he870216_0
  - readline=8.3=hc2a1206_0
  - setuptools=75.1.0=py38h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - sysroot_linux-64=2.17=h0157908_18
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.44.0=py38h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - absl-py==2.3.1
      - annotated-types==0.7.0
      - appdirs==1.4.4
      - cffi==1.17.1
      - charset-normalizer==3.4.4
      - click==8.1.8
      - cloudpickle==3.1.2
      - cycler==0.12.1
      - cython==0.29.24
      - dm-control==1.0.23
      - dm-env==1.6
      - dm-tree==0.1.8
      - docker-pycreds==0.4.0
      - etils==1.3.0
      - eval-type-backport==0.3.1
      - fasteners==0.20
      - filelock==3.13.1
      - fonttools==4.57.0
      - fsspec==2024.6.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - glfw==2.10.0
      - gym==0.23.1
      - gym-notices==0.1.0
      - h5py==3.11.0
      - idna==3.11
      - imageio==2.35.1
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - jinja2==3.1.6
      - kiwisolver==1.4.7
      - labmaze==1.0.6
      - lxml==6.0.2
      - mako==1.3.10
      - markupsafe==2.1.5
      - matplotlib==3.5.2
      - meson==0.59.4
      - mjrl==1.0.0
      - mpmath==1.3.0
      - mujoco==3.2.3
      - mujoco-py==2.1.2.14
      - networkx==3.0
      - ninja==1.10.2
      - numpy==1.24.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - packaging==25.0
      - pandas==2.0.3
      - patchelf==0.17.2.4
      - pathtools==0.1.2
      - pillow==8.4.0
      - platformdirs==4.3.6
      - protobuf==4.25.8
      - psutil==7.2.1
      - pybullet==3.2.7
      - pycparser==2.23
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pyopengl==3.1.10
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pytorch-ranger==0.1.1
      - pytz==2025.2
      - pyyaml==6.0.3
      - requests==2.32.4
      - scipy==1.10.1
      - seaborn==0.11.1
      - sentry-sdk==2.47.0
      - setproctitle==1.3.7
      - six==1.15.0
      - smmap==5.0.2
      - sympy==1.13.3
      - termcolor==2.4.0
      - torch==2.4.1+cu121
      - torch-optimizer==0.3.0
      - torchaudio==2.4.1+cu121
      - torchvision==0.19.1+cu121
      - tqdm==4.67.1
      - triton==3.0.0
      - typing-extensions==4.13.2
      - tzdata==2025.3
      - urllib3==2.2.3
      - wandb==0.23.0
      - zipp==3.20.2
prefix: /mnt/petrelfs/dongjinzong/miniconda3/envs/OfflineRL
